### ISSUE TITLE
AttributeError following addition of ".title()"

### ISSUE THREAD

**Issue by YoruTen** [Wonderfall/ATOS#1]
After ".title()" was added to  "game": bracket["game_name"].title() I get the following error. removing  ".title()" fixes this. 

`File "c:/PATH/bot.py", line 285, in setup_tournament
    tournoi = await get_tournament(url)
  File "c:/PATH/bot.py", line 261, in get_tournament
    "game": bracket["game_name"].title(), # Non-recognized games are lowercase for Challonge
AttributeError: 'NoneType' object has no attribute 'title'`

**Comment by Wonderfall** [comment]
Hi,
Since `bracket['game_name']` was `None`, it seems like it didn't retrieve the game name from Challonge at all. You have to tell the game to Challonge when you set up the tournament, otherwise it cannot recognize the game. :)

(Documentation and english translation are coming soon, btw.)

**Comment by Wonderfall** [comment]
Hey, sorry for the delay. ATOS rewrite should support localization properly. [More info here!](https://atos.laggron.red/)
